name: Cilium Test Results

on:
  workflow_dispatch:

permissions: read-all

jobs:
  cilium-tests:
    name: Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0
        with:
          comment_on_pr: false