name: Cilium Test Results

on:
  workflow_dispatch:
    inputs:
      test_results:
        description: 'Base64 results'
        type: string
        required: true
permissions: read-all
  
  jobs:
    log-the-inputs:
      runs-on: ubuntu-latest
      steps:

jobs:
  cilium-tests:
    name: Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0
        with:
          comment_on_pr: false

      - name: Make JUnit report directory
        run: |
          mkdir -p cilium-junits

      - run: |
          echo $ENVIRONMENT | base64 -d > cilium-junits/test.xml
        env:
          ENVIRONMENT: ${{ inputs.test_results }}

      - name: Upload JUnits [junit]
        if: ${{ always() }}
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: cilium-junits
          path: cilium-junits/*.xml
          retention-days: 2

      - name: Publish Test Results As GitHub Summary
        if: ${{ always() }}
        uses: aanm/junit2md@332ebf0fddd34e91b03a832cfafaa826306558f9 # v0.0.3
        with:
          junit-directory: "cilium-junits"